### ISSUE TITLE
(Empty JSON Request)

### ISSUE THREAD

**Issue by shamoke** [dnsev-h/x-links#10]
https://a.cuntflaps.me/7oyFi.png
Started noticing this today. Probably related to the recent site changes.

**Comment by Daiz** [comment]
Just a matter of updating the E-Hentai API URL, see https://github.com/Hupotronic/ExLinks/commit/b2590e7d8c2b6dbd4d87a97610d4bc109a816c9e

**Comment by lAlexl7l** [comment]
Sorry for the dumb question but that is for the exlinks.js but the xlinks js is a little different and when i locate the url if i change to e-hentai the preview doesnt show any more just the link what can i do here?
