### ISSUE TITLE
regular e-hentai links not resolving

### ISSUE THREAD

**Issue by shamoke** [dnsev-h/x-links#12]
https://a.safe.moe/5gkFx.png

Someone told me it can be fixed by editing var domains which does work.

**Comment by hotdogls321** [comment]
It's still not ok for me... Links on the forums are still the original address.

**Comment by dnsev-h** [comment]
For reference: here is a link to the thread https://boards.4chan.org/h/thread/4538084#p4545119
I'll check into this.

**Comment by hotdogls321** [comment]
Thank you. I'm talking about forums.
For example:https://forums.e-hentai.org/index.php?showtopic=184081&st=3600
the links can not be read.

**Comment by dnsev-h** [comment]
Issue should now be resolved on all supported sites.
