### ISSUE TITLE
Firefox 57

### ISSUE THREAD

**Issue by darkred3** [dnsev-h/x-links#13]
Doesn't seem to be working with firefox 57 and greasemonkey 4.0. Always get "(Connection Error)"

**Comment by dnsev-h** [comment]
Greasemonkey 4 is not backwards compatible with previous versions. I'll have to update the script to support it. As a potential temporary workaround, I've heard other userscript engines may work (Violentmonkey.)

**Comment by mrderp** [comment]
Works with Tampermonkey, although I get "connection error" for Twitter links. Not sure if that's a problem on my end or what.
