### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ragglefraggleee** [dnsev-h/x-links#5]
So i tried asking around and i couldnt really find an answer but everytime i click on the exhentai button it always pops up as error. i tried it with many different posts but everytime it'll say uploading and then error

**Comment by dnsev-h** [comment]
I assume you mean [the link near the image](https://cloud.githubusercontent.com/assets/10576365/15876601/44f4d88e-2cdc-11e6-88b1-bc4a84e70f0e.png).

What browser are you using and what userscript manager?

**Comment by ragglefraggleee** [comment]
yes that link. im using firefox and greasemonkey

**Comment by dnsev-h** [comment]
Could you copy your config settings to here? Open X-Links settings and the click "Export" up at the top.

**Comment by ragglefraggleee** [comment]
like the user script? i cant seem to find the settings. only thing i can find is the options under neath x-links and it only brings up the user scripts.

**Comment by dnsev-h** [comment]
It's at the top of the page on 4chan, a link that looks like [[X-Links](#)], or in the drop-down menu if you use 4chan-x. Though it seems unlikely that you'd have changed anything in there if you don't know where to find it.

Do you have any other addons/userscripts that could affect it?

**Comment by ragglefraggleee** [comment]
i have 4chanx, ex links, exhentai easy, and eze

**Comment by dnsev-h** [comment]
So if the text shows up as just "error", there should be some details about the error when you hover over the "error" link.

For example:
![example image](https://cloud.githubusercontent.com/assets/10576365/15992264/db1f51dc-3096-11e6-9e76-bfc1686cc6e4.png)

Can you try this and see if it does indeed pop it up? Try to get me a screenshot of the error and the hovering message.

**Comment by ragglefraggleee** [comment]
![untitled](https://cloud.githubusercontent.com/assets/19787558/15993443/0d1d5cdc-30ac-11e6-8b2d-92af36939925.png)

**Comment by dnsev-h** [comment]
Alright this is a helpful start, could you also do the same thing except on a post with a .PNG image?

Following that, I can probably get you some instructions on how to help me pinpoint where this is coming from.

**Comment by ragglefraggleee** [comment]
pngs seem to say found:0

**Comment by dnsev-h** [comment]
Okay, so this next part is a few steps, but it should basically tell me exactly what's going wrong.

1. [Open settings](https://cloud.githubusercontent.com/assets/10576365/16025916/823e4ffc-3198-11e6-8728-240adebec031.png) and check the option "[Debugging > Enabled](https://cloud.githubusercontent.com/assets/10576365/16025937/a126cd4a-3198-11e6-96da-f7d9679a1e8f.png)" <br /><br />

2. Refresh the page <br /><br />

3. Open the developer console by pressing CTRL+SHIFT+K <br /><br />

4. Find a **JPG** image and get the error you've been having <br /><br />

5. In the developer console, you should see a bunch of diagnostic lines, one prefixed with: <br />
  ```X-Links 1.2.8.9: An error occured while reverse image searching``` <br />
  and then some more info after it. If you click on the word "Object" in this message, it should open a second panel to the right.
  [image](https://cloud.githubusercontent.com/assets/10576365/16025946/b4b5be20-3198-11e6-8ca8-d16493b5c01c.png)<br /><br />

6. In this panel, there are 4 relevant fields that will help: <br />
  ```finalUrl```, ```responseHeaders```, ```responseText```, and ```status``` <br />
  Click the content to the right of each label and paste it into a comment on here. Some of them may be fairly lengthy.
  [image](https://cloud.githubusercontent.com/assets/10576365/16025958/c9632a24-3198-11e6-941c-81ed9d53f91e.png)

---

This is a lot of steps just to try and diagnose the error, but it's not something I am able to reproduce with my setup.

**Comment by ragglefraggleee** [comment]
http://exhentai.org/?poni=NzE3MDc2LTNmZmQ1NTIwMjIwZDk0NDQwNDdmYTUxMDQ0YjEyYjA5LTE0NjU4ODkyNjEtMDVjMjU0OTY3ZTIxMDM0M2YzNWM3YTA3M2YxZGQ0MDhiN2IxZDFmMw==

"<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><title>ExHentai.org</title><link rel="stylesheet" type="text/css" href="http://exhentai.org/z/0319/x.css" /></head><body style="text-align:center"><script type="text/javascript">function popUp(URL,w,h) { 	window.open(URL,"_pu"+(Math.random()+"").replace(/0\./,""),"toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width="+w+",height="+h+",left="+((screen.width-w)/2)+",top="+((screen.height-h)/2));	return false;}</script><p id="nb"><img src="http://exhentai.org/img/mr.gif" alt="" /> <a href="http://exhentai.org/">Front Page</a><img src="http://exhentai.org/img/mr.gif" alt="" /> <a href="http://exhentai.org/torrents.php">Torrents</a><img src="http://exhentai.org/img/mr.gif" alt="" /> <a href="http://exhentai.org/favorites.php">Favorites</a><img src="http://exhentai.org/img/mr.gi"

"<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><title>ExHentai.org</title><link rel="stylesheet" type="text/css" href="http://exhentai.org/z/0319/x.css" /></head><body style="text-align:center"><script type="text/javascript">function popUp(URL,w,h) { 	window.open(URL,"_pu"+(Math.random()+"").replace(/0\./,""),"toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width="+w+",height="+h+",left="+((screen.width-w)/2)+",top="+((screen.height-h)/2));	return false;}</script><p id="nb"><img src="http://exhentai.org/img/mr.gif" alt="" /> <a href="http://exhentai.org/">Front Page</a><img src="http://exhentai.org/img/mr.gif" alt="" /> <a href="http://exhentai.org/torrents.php">Torrents</a><img src="http://exhentai.org/img/mr.gif" alt="" /> <a href="http://exhentai.org/favorites.php">Favorites</a><img src="http://exhentai.org/img/mr.gi"

200

**Comment by dnsev-h** [comment]
Alright, so I'm not sure exactly what the redirect is for, but your being redirected to an incorrect page. My guess would be it has something to do with cookies and/or the ExHentai Easy plugin.

I would recommend trying to change the "ExSauce > Lookup domain" option in X-Links to "g.e-hentai.org" and see how that affects things.

**Comment by ragglefraggleee** [comment]
does exlinks not work with .jpgs? i saved an image straight from g.e and posted it and i still get error but this time it says no file was uploaded or the file uploaded is invalid

**Comment by dnsev-h** [comment]
It should work. I'm not sure what happened when you used the ExHentai site to search, but if you notice that the URL changes into something like:<br />
```http://exhentai.org/?poni=<letters>```<br />
after uploading, that indicates you're getting the error.

I would recommend logging into E-Hentai in an incognito tab _without_ using the ExHentai Easy script and see if you can search an image then. (Temporarily disable Greasemonkey)

[How-to video](https://data.desustorage.org/a/image/1452/03/1452039367372.webm)

If that works, then the issue is that you have some bad cookies that are breaking things.

**Comment by ragglefraggleee** [comment]
i guess im just doomed

**Comment by ragglefraggleee** [comment]
also exhentai's file search doesnt seem to work for me whereas g.e does work

**Comment by ragglefraggleee** [comment]
I GOT IT TO WORK. After constantly deleting cookies one after another and disabling add ons over and over. i just gave up and turned everything back on and deleted cookies just for exhentai and now it is magically working

**Comment by dnsev-h** [comment]
So it seems like it was a cookie issue as I suspected. The reason for this may have been that reverse-image-search using similarity scan uploads to ```ul.exhentai.org```, and while you may have had correct cookies for ```exhentai.org```, perhaps the cookies for ```ul.exhentai.org``` were erroneous.

I presume it is now working in X-Links also. Let me know if that is not the case.

I will add some code to the script to try to make the error message more meaningful for anyone who may encounter this problem in the future.

Thank you for your time helping me debug this.

**Comment by ragglefraggleee** [comment]
well i deleted the cookies several times so idk what the real issue was.

**Comment by dnsev-h** [comment]
exhentai a shit
