### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by decentblack** [dnsev-h/x-links#7]
Hi, I'm having the same issue that user ragglefraggleee had back in June. When I try to use the x-links reverse search button, I get "Unknown error":
![untitled](https://cloud.githubusercontent.com/assets/22783732/19296462/880cbbba-8ff0-11e6-9972-11369d03dfa6.png)
When I try to reverse search a .png, I get "found:0".
Following the debugging instructions you gave before (clicking "Object" in the developer console), here is what I have:

finalUrl: https://exhentai.org/

responseHeaders:"Date: Wed, 12 Oct 2016 03:25:18 GMTServer: ApacheSet-Cookie: uconfig=uh_y-lt_m-rc_0-tl_r-cats_0-xns_0-ts_m-tr_2-prn_y-dm_l-ar_0-rx_0-ry_0-ms_n-mt_n-cs_a-fs_p-to_a-pn_0-sc_0-ru_rrggb-xr_a-sa_y-oi_n-qb_n-tf_n-hh_-hp_-hk_-xl_; expires=Thu, 12-Oct-2017 03:25:18 GMT; Max-Age=31536000; path=/; domain=.exhentai.orglv=1476242130-1476242718; expires=Thu, 12-Oct-2017 03:25:18 GMT; Max-Age=31536000; path=/Cache-Control: no-cacheVary: Accept-EncodingContent-Encoding: gzipContent-Length: 6643Content-Type: text/html; charset=UTF-8x-varnish: 345545861Age: 0Via: 1.1 varnish-v4Accept-Ranges: bytesstrict-transport-security: max-age=31536000; preload;"

responseText:"<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><title>ExHentai.org</title><link rel="stylesheet" type="text/css" href="https://exhentai.org/z/0323/x.css" /></head><body style="text-align:center"><script type="text/javascript">function popUp(URL,w,h) {	window.open(URL,"_pu"+(Math.random()+"").replace(/0\./,""),"toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width="+w+",height="+h+",left="+((screen.width-w)/2)+",top="+((screen.height-h)/2));	return false;}</script><p id="nb"><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/">Front Page</a><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/torrents.php">Torrents</a><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/favorites.php">Favorites</a><img src="https://exhentai.org/im"

status:200

I've tried deleting all my cookies as the guy did before, but it doesn't help. I am not using any exhentai related plugins, only cookiemanager.

**Comment by dnsev-h** [comment]
What browser are you using?

And is there any additional text inside of "responseText"? Usually browsers truncate it if it's too long.

**Comment by decentblack** [comment]
I am using Waterfox. 

I tried reverse searching another picture, here's what the responseText this time:
"<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><title>ExHentai.org</title><link rel="stylesheet" type="text/css" href="https://exhentai.org/z/0323/x.css" /></head><body style="text-align:center"><script type="text/javascript">function popUp(URL,w,h) {	window.open(URL,"_pu"+(Math.random()+"").replace(/0\./,""),"toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width="+w+",height="+h+",left="+((screen.width-w)/2)+",top="+((screen.height-h)/2));	return false;}</script><p id="nb"><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/">Front Page</a><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/torrents.php">Torrents</a><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/favorites.php">Favorites</a><img src="https://exhentai.org/im""<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head><title>ExHentai.org</title><link rel="stylesheet" type="text/css" href="https://exhentai.org/z/0323/x.css" /></head><body style="text-align:center"><script type="text/javascript">function popUp(URL,w,h) {	window.open(URL,"_pu"+(Math.random()+"").replace(/0\./,""),"toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width="+w+",height="+h+",left="+((screen.width-w)/2)+",top="+((screen.height-h)/2));	return false;}</script><p id="nb"><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/">Front Page</a><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/torrents.php">Torrents</a><img src="https://exhentai.org/img/mr.gif" alt="" /> <a href="https://exhentai.org/favorites.php">Favorites</a><img src="https://exhentai.org/im"

**Comment by dnsev-h** [comment]
Fixed in [1.2.8.15](https://github.com/dnsev-h/x-links/commit/a4357654cd9cd21027b88bb2cc5bca83669fdfb9). Apparently the upload URLs were changed for similarity search.
