### ISSUE TITLE
Similarity lookup does not work on monotone images (jpg)

### ISSUE THREAD

**Issue by decentblack** [dnsev-h/x-links#8]
Hi, the last update made the script able to consistently reverse search .pngs for me, but now when I try to reverse search .jpgs, I get a different error:
![error](https://cloud.githubusercontent.com/assets/22783732/19397622/6228a97c-91fd-11e6-9711-a2e76d320ecf.png)

**Comment by dnsev-h** [comment]
This has always been the case since 4chan started modifying JPEG images. See [original issue](https://github.com/Hupotronic/ExLinks/pull/58). Unfortunately there is nothing that can be done about this.

**Comment by decentblack** [comment]
I see, thanks for the support.
